### ISSUE TITLE
Installing the CMake build of oomph-lib on MacOS requires root permission.

### ISSUE THREAD

**Issue by RupinderM** [PuneetMatharu/oomph-lib#1]
Running the following command in oomph-lib/build
> ninja install

[0/1] Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/lib/oomphlib/liboomph_hsld.a
CMake Error at external_src/oomph_hsl/cmake_install.cmake:49 (file):
  file INSTALL cannot copy file
  "/Users/rupinder/Coding/C++/oomph-lib/build/external_src/oomph_hsl/liboomph_hsld.a"
  to "/usr/local/lib/oomphlib/liboomph_hsld.a": Permission denied.
Call Stack (most recent call first):
  external_src/cmake_install.cmake:42 (include)
  cmake_install.cmake:42 (include)

FAILED: CMakeFiles/install.util
cd /Users/rupinder/Coding/C++/oomph-lib/build && /Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.

**Comment by puneetmatharu** [comment]
Patched with [commit `b999818f`.](https://github.com/puneetmatharu/oomph-lib/tree/b999818fabb4ec14460fec9ab00019b5e05931d4).
