### ISSUE TITLE
Issue with test configuration files

### ISSUE THREAD

**Issue by RupinderM** [PuneetMatharu/oomph-lib#4]
When configuring a specific demo_driver inside its respective folder, and the oomph-lib install is specified by --install-prefix, running ctest in the build folder returns
\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
No test configuration file found!
\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
Usage

  ctest [options].
  
I believe this arises since certain files (CTestTestfile.cmake, Testing and DartConfiguration.tcl in the case of the adaptive_tet_meshes demo driver) are not copied into the build directory.

**Comment by RupinderM** [comment]
It was not the position of the oomph-lib install that was the issue. Building oomph-lib with OOMPH_WANT_CGAL=ON causes certain files not to be copied into the build directory.

**Comment by puneetmatharu** [comment]
Patched with fd27bd8a84ff73ae2dc20d9dfa1f10d23033555e.
